"""The ingestion serving API, deployed with its two DynamoDB tables.

Feature: personal-diary-memory (Requirements 3.2, 4.2, 5.1, 7.1, 7.2, 8.1, 8.4).

This stack turns the advisor's dormant memory on: it provisions the ``profiles``
and ``symptom-log`` tables the ingestion service's DynamoDB adapters expect, and a
serving Lambda configured to select those adapters and the Cognito authenticator.

Three things are load-bearing and worth stating, because each is what a
well-meaning edit could silently reverse:

* **The table key attributes are not free choices.** ``DynamoDbProfileStore`` reads
  ``Key={"user_id": ...}`` and ``DynamoDbSymptomLogStore`` reads
  ``Key={"user_id", "entry_date"}`` and queries the ``entry_date`` sort key. The
  partition/sort attribute names here MUST match those literals, so the names come
  from the adapter source, not a guess.
* **The environment selects the real adapters.** The ingestion config loader picks
  an adapter per port from ``AQM_ADAPTER_<PORT_UPPER>``, and reads the table names
  from ``AQM_TABLE_PROFILES`` (``_table("profiles")``) and ``AQM_SYMPTOM_LOG_TABLE``
  (``_required_setting(...)``). Those exact keys are set below; the table names are
  the CDK-generated names, passed via ``table.table_name`` so nothing is hard-coded.
* **IAM is scoped to exactly the two tables.** ``grant_read_write_data`` scopes the
  DynamoDB actions to each table's ARN (and its indexes), never ``Resource: "*"``.
  The serving adapters use GetItem/PutItem/Query/DeleteItem/Scan; that grant is a
  superset, so least privilege holds without enumerating actions by hand.

Cognito ids arrive as constructor params, required at DEPLOY but not at synth: a
synth with ``None`` placeholders still succeeds (keeping ``cdk synth``
credential-free for CI), and the deploy is refused without them. Table names are
generated by CDK, so nothing about identity or storage is committed.
"""

from __future__ import annotations

import aws_cdk as cdk
from aws_cdk import (
    BundlingOptions,
    CfnOutput,
    Duration,
    RemovalPolicy,
    Stack,
)
from aws_cdk import aws_apigatewayv2 as apigw
from aws_cdk import aws_apigatewayv2_integrations as integrations
from aws_cdk import aws_dynamodb as dynamodb
from aws_cdk import aws_lambda as lambda_
from aws_cdk import aws_logs as logs
from constructs import Construct


class IngestionServingStack(Stack):
    """The serving Lambda plus the ``profiles`` and ``symptom-log`` DynamoDB tables."""

    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        *,
        service_dir: str,
        region: str,
        cognito_user_pool_id: str | None,
        cognito_client_id: str | None,
        cognito_issuer: str | None,
        env: cdk.Environment | None = None,
        description: str | None = None,
    ) -> None:
        """Provision the tables, the serving Lambda, its HTTP API, and least-privilege IAM.

        Args:
            scope: the CDK app or parent construct.
            construct_id: the stack's logical id.
            service_dir: the ingestion service source directory to bundle
                (``../data-processing``).
            region: the deploy region, carried to the Lambda as ``AQM_AWS_REGION``.
            cognito_user_pool_id: the Cognito user pool id the authenticator verifies
                against; required at DEPLOY, ``None`` is allowed at synth.
            cognito_client_id: the Cognito app client id; required at deploy.
            cognito_issuer: the Cognito issuer URL used to fetch JWKS; required at deploy.
            env: the target account and region, set EXPLICITLY so synthesis performs
                no account lookup.
            description: an optional CloudFormation stack description.
        """
        super().__init__(scope, construct_id, env=env, description=description)

        # --- The two DynamoDB tables ------------------------------------------------
        #
        # Both PAY_PER_REQUEST (no capacity to plan for a POC), encrypted at rest
        # (health-adjacent data, Req 5.1), and RemovalPolicy.DESTROY so the POC tears
        # down cleanly (Req 7.4). AWS_MANAGED encryption keeps the table key off the
        # cost sheet while still satisfying encryption-at-rest.

        # profiles: partition key user_id (S) only. Matches DynamoDbProfileStore's
        # Key={"user_id": ...} — the identity IS the key, there is no sort key.
        profiles_table = dynamodb.Table(
            self,
            "ProfilesTable",
            partition_key=dynamodb.Attribute(
                name="user_id", type=dynamodb.AttributeType.STRING
            ),
            billing_mode=dynamodb.BillingMode.PAY_PER_REQUEST,
            encryption=dynamodb.TableEncryption.AWS_MANAGED,
            removal_policy=RemovalPolicy.DESTROY,
        )

        # symptom-log: partition key user_id (S), sort key entry_date (S, an ISO date
        # string). Matches DynamoDbSymptomLogStore's Key={"user_id", "entry_date"} and
        # its entry_date range queries. The reserved "#learned" sort key the store
        # files Learned_Thresholds under is a value, not a schema attribute, so it
        # needs no separate declaration.
        symptom_log_table = dynamodb.Table(
            self,
            "SymptomLogTable",
            partition_key=dynamodb.Attribute(
                name="user_id", type=dynamodb.AttributeType.STRING
            ),
            sort_key=dynamodb.Attribute(
                name="entry_date", type=dynamodb.AttributeType.STRING
            ),
            billing_mode=dynamodb.BillingMode.PAY_PER_REQUEST,
            encryption=dynamodb.TableEncryption.AWS_MANAGED,
            removal_policy=RemovalPolicy.DESTROY,
        )

        # --- The serving Lambda's environment ---------------------------------------
        #
        # Selects the real adapters (AQM_ADAPTER_<PORT_UPPER>) and the cognito
        # authenticator, disables the ingest/push paths, and carries the table names
        # (the CDK-generated names, via table.table_name) plus the Cognito ids. Cold
        # start's resolve_and_validate fails fast on a missing table or Cognito id
        # (Req 8.5), so a half-configured request path never serves.
        fn_env = {
            "AQM_ENABLE_SERVING": "true",
            "AQM_ENABLE_PULL": "false",
            "AQM_ENABLE_PUSH": "false",
            "AQM_AWS_REGION": region,
            "AQM_LOG_LEVEL": "info",
            # Adapter selection: the loader reads AQM_ADAPTER_<PORT_UPPER>.
            "AQM_ADAPTER_PROFILE_STORE": "dynamodb",
            "AQM_ADAPTER_SYMPTOM_LOG_STORE": "dynamodb",
            "AQM_ADAPTER_AUTHENTICATOR": "cognito",
            # Table names: the exact keys the composition reads. Generated names,
            # so nothing storage-related is committed.
            "AQM_TABLE_PROFILES": profiles_table.table_name,
            "AQM_SYMPTOM_LOG_TABLE": symptom_log_table.table_name,
            # Cognito ids: required at deploy, empty placeholders at synth so the
            # offline suite resolves nothing from an account.
            "AQM_COGNITO_USER_POOL_ID": cognito_user_pool_id or "",
            "AQM_COGNITO_CLIENT_ID": cognito_client_id or "",
            "AQM_COGNITO_ISSUER": cognito_issuer or "",
        }

        # The Cognito ids are required at DEPLOY, not synth. A synth with none still
        # succeeds (keeps `cdk synth` credential-free for CI); deploying without them
        # is refused rather than shipping an authenticator that verifies against
        # nothing.
        for name, value in (
            ("cognito_user_pool_id", cognito_user_pool_id),
            ("cognito_client_id", cognito_client_id),
            ("cognito_issuer", cognito_issuer),
        ):
            if not value:
                cdk.Annotations.of(self).add_error(
                    f"{construct_id}: no {name}. Deploy with the Cognito ids from the "
                    "CognitoStack outputs (synth succeeds without them; deploy does not)."
                )

        # Bundle the service source + pinned deps with uv, ARM64 to match the ARM_64
        # function below. The chatbot stack's pattern: CDK runs bundling as uid 1000
        # with no writable HOME, so point every cache at /tmp or uv fails on /.cache.
        code = lambda_.Code.from_asset(
            service_dir,
            bundling=BundlingOptions(
                platform="linux/arm64",
                image=cdk.DockerImage("public.ecr.aws/sam/build-python3.12:latest-arm64"),
                command=[
                    "bash",
                    "-c",
                    " && ".join(
                        [
                            "export HOME=/tmp XDG_CACHE_HOME=/tmp UV_CACHE_DIR=/tmp/uv-cache "
                            "PIP_CACHE_DIR=/tmp/pip-cache",
                            "pip install uv -q",
                            "uv export --frozen --no-dev --no-emit-project "
                            "-o /tmp/req.txt 2>/dev/null || "
                            "uv pip compile pyproject.toml -o /tmp/req.txt",
                            "pip install -r /tmp/req.txt -t /asset-output -q",
                            "cp -r src/* /asset-output/",
                        ]
                    ),
                ],
            ),
        )

        fn = lambda_.Function(
            self,
            "Fn",
            runtime=lambda_.Runtime.PYTHON_3_12,
            architecture=lambda_.Architecture.ARM_64,
            handler="aqm_ingestion.lambda_handler.handler",
            code=code,
            timeout=Duration.seconds(29),  # HTTP API integration ceiling
            memory_size=1024,
            environment=fn_env,
            log_retention=logs.RetentionDays.ONE_WEEK,
        )

        # Least privilege: the serving adapters read and write only these two tables.
        # grant_read_write_data scopes GetItem/PutItem/Query/DeleteItem/Scan/etc. to
        # each table ARN (and its indexes), never Resource: "*".
        profiles_table.grant_read_write_data(fn)
        symptom_log_table.grant_read_write_data(fn)

        http_api = apigw.HttpApi(
            self,
            "HttpApi",
            default_integration=integrations.HttpLambdaIntegration("Integration", fn),
        )

        CfnOutput(self, "ApiUrl", value=http_api.api_endpoint)
        CfnOutput(self, "FunctionName", value=fn.function_name)
        CfnOutput(self, "ProfilesTableName", value=profiles_table.table_name)
        CfnOutput(self, "SymptomLogTableName", value=symptom_log_table.table_name)


__all__ = ["IngestionServingStack"]
