"""The AI Advisor Agent (Service 3): guidance from Service 2's per-user view.

A Strands agent whose loop runs in this process, deployed as a container to Amazon Bedrock
AgentCore Runtime. It has one organising idea and one hazard.

**It composes and verifies; it does not compute.** Service 2 already derives the condition
weighting, the escalation threshold and which thresholds were crossed, the inhaled dose, the
forecast and pollen outlook, the confidence flags, and the provenance of every number. Every
quantitative claim in the guidance is therefore a value that arrived in a retrieval, and the job
here is to make an invented number UNREPRESENTABLE rather than merely discouraged. An agent that
recalculated a sub-index would produce a number disagreeing with what the API served, with
nothing to reconcile them.

**The output is generated by a language model**, which is the one place in this system where a
constraint can be violated by text nobody wrote. Every guardrail is therefore a check on the
emitted text, applied after generation at a point no return path can bypass, and it fails
closed:
an unverifiable health-adjacent generation is worse than none.

Layering, enforced by the AST checks of task 2.5 rather than by convention:

    agentcore/ ──► agent/ ──► ports/ ──► domain/
    adapters/  ──► ports/

Nothing under ``domain/`` imports ``adapters/`` or ``agentcore/``, reads the wall clock, or
imports ``random``. Only ``agentcore/`` imports the deployment SDK, so the advisory turn is
runnable — and the whole suite passes — with no AWS credentials and no network beyond
localhost.
"""
